wowlinks:
  "codingrepo": "https://github.com/tianhaoz95-notebooks/coding-interview"
  "coding": "https://tianhaoz95-notebooks.github.io/coding-interview"
  "h": "https://github.com/tianhaoz95-notebooks"
