wowlinks:
  # OA stands for online assesment which is usually the name for this
  # type of coding interviews.
  "oa": "https://tianhaoz95-notebooks.github.io/coding-interview"
  # WS stands for workstation
  "ws": "https://tianhaoz95-notebooks.github.io/workstation-setup"
  # GH stands for GitHub which points to GitHub related notes
  "gh": "https://tianhaoz95-notebooks.github.io/github-notes"
  # ML stands for Machine Learning which points to machine learning
  # related notes.
  "ml": "https://tianhaoz95-notebooks.github.io/github-notes"
  # FS stands for Full-Stack which points to full-stack related notes.
  "fs": "https://tianhaoz95-notebooks.github.io/fullstack-notes"
  # MB stands for Mobile which points to mobile development related notes.
  "mb": "https://tianhaoz95-notebooks.github.io/mobile-notes"
  # H stands for home which is the org root for all notebooks
  "h": "https://github.com/tianhaoz95-notebooks"
